stages:
  - build_docker
  - build
  - test
  - analysis
  - deploy
  - pages

#############################
# Build docker
#############################

.build:docker:
  stage: build_docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  when: manual
  tags:
    - docker

.build:docker:minreq_ci:
  extends: .build:docker
  script:
    - |
      /kaniko/executor \
      --context $CI_PROJECT_DIR \
      --dockerfile $CI_PROJECT_DIR/docker/minreq_ci/Dockerfile \
      --destination $CI_REGISTRY_IMAGE/minreq_ci:$CI_COMMIT_TAG

build:docker:minreq_ci:latest:
  extends: .build:docker:minreq_ci
  variables:
    CI_COMMIT_TAG: "latest"

#############################
# Build delegates
#############################

.build:linux:
  stage: build
  script:
    - cmake -DROME_DELEGATES_BUILD_TESTS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_COMPILER:FILEPATH=clang++-4.0 -G Ninja -B build
    - cmake --build build --config Release --target unittests
  tags:
    - docker
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/build/
    expire_in: 1 hrs

build:linux:minreq_ci:
  extends: .build:linux
  image: registry.gitlab.com/rmettler/cpp_delegates/minreq_ci:latest

#############################
# Test delegates
#############################

.test:linux:
  stage: test
  script:
    - ninja -C build run_all_tests
  tags:
    - docker

test:linux:minreq_ci:
  extends: .test:linux
  image: registry.gitlab.com/rmettler/cpp_delegates/minreq_ci:latest
  dependencies: 
    - build:linux:minreq_ci
  needs: ["build:linux:minreq_ci"]
  